DROP TABLE IF EXISTS `farmer_traces`;

CREATE TABLE `farmer_traces` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT COMMENT '自动ID',
  `farmer_id` int(11) unsigned NOT NULL COMMENT '农民序号',
  `time` datetime DEFAULT NULL COMMENT '模拟时间',
  `remaining_water` double(8, 2) DEFAULT NULL COMMENT '可用水量(m^3)',
  `precip` double(8, 2) DEFAULT NULL COMMENT '降雨量(mm)',
  `eto` double(8, 2) DEFAULT NULL COMMENT '参考作物腾发量(mm)',
  `zr_rice` double(8, 2) DEFAULT NULL COMMENT '水稻根系层深度(m)',
  `raw_rice` double(8, 2) DEFAULT NULL COMMENT '水稻易被吸收的有效水量(mm)',
  `irri_rice` double(8, 2) DEFAULT NULL COMMENT '水稻灌溉量(mm)',
  `kc_rice` double(8, 2) DEFAULT NULL COMMENT '水稻的作物系数',
  `etc_rice` double(8, 2) DEFAULT NULL COMMENT '水稻腾发量(mm)',
  `ks_rice` double(8, 2) DEFAULT NULL COMMENT '水稻的水分胁迫系数',
  `etcadj_rice` double(8, 2) DEFAULT NULL COMMENT '水稻水分胁迫下的腾发量(mm)',
  `dr_rice` double(8, 2) DEFAULT NULL COMMENT '水稻土壤根系层的消耗水量(mm)',
  `yield_rice` double(8, 2) DEFAULT NULL COMMENT '水稻的累计产量(Kg/mu)',
  `zr_maize` double(8, 2) DEFAULT NULL COMMENT '玉米根系层深度(m)',
  `raw_maize` double(8, 2) DEFAULT NULL COMMENT '玉米易被吸收的有效水量(mm)',
  `irri_maize` double(8, 2) DEFAULT NULL COMMENT '玉米灌溉量(mm)',
  `kc_maize` double(8, 2) DEFAULT NULL COMMENT '玉米的作物系数',
  `etc_maize` double(8, 2) DEFAULT NULL COMMENT '玉米腾发量(mm)',
  `ks_maize` double(8, 2) DEFAULT NULL COMMENT '玉米的水分胁迫系数',
  `etcadj_maize` double(8, 2) DEFAULT NULL COMMENT '玉米水分胁迫下的腾发量(mm)',
  `dr_maize` double(8, 2) DEFAULT NULL COMMENT '玉米土壤根系层的消耗水量(mm)',
  `yield_maize` double(8, 2) DEFAULT NULL COMMENT '玉米的累计产量(Kg/mu)',
  `created_at` datetime DEFAULT NULL COMMENT '创建时间',
  `updated_at` datetime DEFAULT NULL COMMENT '更新时间',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;